### PR TITLE
Add TimeUtils.iso_string_to_epoch_seconds

### PR DESCRIPTION
**Pull request by as2388**

### CODE REVIEW

**Comment by lukechurch** [comment]
Can you provide a short note as to what we want to use this for?

**Comment by as2388** [comment]
Converting Coda's time format to that of Metadata

**Comment by lukechurch** [comment]
Can we change metadata to use an ISO string instead?

**Comment by as2388** [comment]
Will begin the process of migrating to utc iso strings instead, closing.

**Pull request closed without merging**
